Feature 857 course module management
johnkallstrom/LexiconLMS pull request #5
Opened 2024-06-20 15:09 UTC by ulfbou

Fixed Dependency Injection

2024-06-20 18:04 UTC, johnkallstrom requested changes
Vi borde inte använda repositories / services direkt i blazor projektet. De är bättre om Patrik tar in dem i API projektet istället. Approvar inte de häärsd sändringarna

2024-06-20 18:08 UTC, johnkallstrom requested changes

2024-06-20 18:08 UTC, johnkallstrom commented on LexiconLMS/Components/CourseOverview.razor
> +        // TeacherCourses = (await UnitOfWork.GetRepository<Course>().FindAsync(c => c.Teacher.UserName == UserName)).ToList();
Borde inte använda repository direkt i component

2024-06-20 18:08 UTC, johnkallstrom commented on LexiconLMS/Components/Shared/Courses.razor
Borde ligga i en egen Course mapp, typ Courses/Components elr ngt

2024-06-20 18:08 UTC, johnkallstrom commented on LexiconLMS/Components/Shared/CourseCard.razor
Samma här, borde ligga i course mapp. 
Typ: 
- Courses
    - Components
    - Pages

2024-06-20 21:04 UTC, ulfbou commented on LexiconLMS/Components/CourseOverview.razor
> +        // TeacherCourses = (await UnitOfWork.GetRepository<Course>().FindAsync(c => c.Teacher.UserName == UserName)).ToList();
ICourseService är rätt för uppgiften.

2024-06-20 21:09 UTC, ulfbou commented on LexiconLMS/Components/Shared/Courses.razor
Tror inte att de utanför Course behövs

2024-06-24 07:01 UTC, SallyResch approved these changes

2024-06-26 12:54 UTC, closed without merging